"""init schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-30 21:32:35.478765
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_answers',
    sa.Column('question_norm', sa.String(), nullable=False),
    sa.Column('question_raw', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('profile_field_ref', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approved_answers'))
    )
    with op.batch_alter_table('approved_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approved_answers_question_norm'), ['question_norm'], unique=False)

    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_companies_normalized_name'))
    )
    op.create_table('cover_letter_templates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('body_md', sa.Text(), nullable=True),
    sa.Column('placeholders', sa.JSON(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cover_letter_templates'))
    )
    op.create_table('field_provenance',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_provenance')),
    sa.UniqueConstraint('table_name', 'row_id', 'column_name', name='uq_field_provenance_target')
    )
    op.create_table('page_snapshots',
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('dom_hash', sa.String(), nullable=True),
    sa.Column('viewport', sa.JSON(), nullable=True),
    sa.Column('frames', sa.JSON(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_snapshots'))
    )
    op.create_table('portals',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('adapter_key', sa.String(), nullable=True),
    sa.Column('search_url_template', sa.Text(), nullable=True),
    sa.Column('automation_policy', sa.String(), nullable=False),
    sa.Column('requires_account', sa.Boolean(), nullable=False),
    sa.Column('tos_risk', sa.String(), nullable=False),
    sa.Column('login_state_ref', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portals')),
    sa.UniqueConstraint('slug', name=op.f('uq_portals_slug'))
    )
    op.create_table('search_runs',
    sa.Column('query', sa.JSON(), nullable=True),
    sa.Column('portals', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('initiated_by', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_runs'))
    )
    op.create_table('user_profile',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('work_auth', sa.String(), nullable=True),
    sa.Column('default_language', sa.String(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_table('certifications',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('issued', sa.String(), nullable=True),
    sa.Column('expires', sa.String(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_certifications_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_table('education',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_education_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    op.create_table('job_postings',
    sa.Column('portal_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('apply_url_norm', sa.String(), nullable=True),
    sa.Column('canonical_job_key', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company_name_raw', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote_type', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('salary_raw', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('tech_tags', sa.JSON(), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('raw_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('dedup_of', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_job_postings_company_id_companies')),
    sa.ForeignKeyConstraint(['dedup_of'], ['job_postings.id'], name=op.f('fk_job_postings_dedup_of_job_postings')),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], name=op.f('fk_job_postings_portal_id_portals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_job_postings_content_hash'))
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_apply_url_norm'), ['apply_url_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_canonical_job_key'), ['canonical_job_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('languages',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('cefr_level', sa.String(), nullable=True),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_languages_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_table('preferences',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(), nullable=True),
    sa.Column('salary_period', sa.String(), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('remote_pref', sa.String(), nullable=False),
    sa.Column('relocation', sa.Boolean(), nullable=False),
    sa.Column('job_titles', sa.JSON(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('seniority_target', sa.String(), nullable=True),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('blacklist_companies', sa.JSON(), nullable=True),
    sa.Column('blacklist_keywords', sa.JSON(), nullable=True),
    sa.Column('submit_mode', sa.String(), nullable=False),
    sa.Column('reapply_policy', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('max_apps_per_day', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_preferences_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences'))
    )
    op.create_table('projects',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_projects_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('publications',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_publications_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications'))
    )
    op.create_table('skills',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('last_used', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_skills_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('work_experience',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('remote', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_work_experience_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_experience'))
    )
    op.create_table('job_matches',
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('penalties', sa.JSON(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=True),
    sa.Column('success_probability', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_job_matches_job_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], name=op.f('fk_job_matches_search_run_id_search_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_matches'))
    )
    op.create_table('applications',
    sa.Column('job_match_id', sa.Integer(), nullable=True),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('field_log', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('confirmation_ref', sa.String(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('reapply_of', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_match_id'], ['job_matches.id'], name=op.f('fk_applications_job_match_id_job_matches')),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], name=op.f('fk_applications_job_posting_id_job_postings')),
    sa.ForeignKeyConstraint(['reapply_of'], ['applications.id'], name=op.f('fk_applications_reapply_of_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_table('action_log',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('target_index', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('snapshot_before_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_after_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_action_log_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log'))
    )
    op.create_table('interventions',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('elicitation_id', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_interventions_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    op.drop_table('action_log')
    op.drop_table('applications')
    op.drop_table('job_matches')
    op.drop_table('work_experience')
    op.drop_table('skills')
    op.drop_table('publications')
    op.drop_table('projects')
    op.drop_table('preferences')
    op.drop_table('languages')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_job_postings_canonical_job_key'))
        batch_op.drop_index(batch_op.f('ix_job_postings_apply_url_norm'))

    op.drop_table('job_postings')
    op.drop_table('education')
    op.drop_table('certifications')
    op.drop_table('user_profile')
    op.drop_table('search_runs')
    op.drop_table('portals')
    op.drop_table('page_snapshots')
    op.drop_table('field_provenance')
    op.drop_table('cover_letter_templates')
    op.drop_table('companies')
    with op.batch_alter_table('approved_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approved_answers_question_norm'))

    op.drop_table('approved_answers')
    # ### end Alembic commands ###
